import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from win_search_aliases.config import load_deny_list
from win_search_aliases.db import ManagedRow
from win_search_aliases.filters import AppCandidate, FilterReport
from win_search_aliases.ui import gui as ui


def test_ui_main_reports_non_windows_without_mainloop(monkeypatch) -> None:
    shown = {}

    class FakeTk:
        def withdraw(self):
            shown["withdraw"] = True

        def destroy(self):
            shown["destroy"] = True

        def iconbitmap(self, **kwargs):
            pass

    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(ui.tk, "Tk", FakeTk)
    monkeypatch.setattr(
        ui, "show_message", lambda _master, _title, message, _kind="info": shown.update(message=message)
    )

    assert ui.main() == 1
    assert shown["message"] == ui.WINDOWS_ONLY_ERROR
    assert shown["withdraw"] is True
    assert shown["destroy"] is True


def test_ui_smoke_test_creates_and_destroys_root(monkeypatch) -> None:
    calls = []

    class FakeTk:
        def withdraw(self):
            calls.append("withdraw")

        def update_idletasks(self):
            calls.append("update_idletasks")

        def destroy(self):
            calls.append("destroy")

        def iconbitmap(self, **kwargs):
            pass

    monkeypatch.setattr(ui.tk, "Tk", FakeTk)

    assert ui.main(["--smoke-test"]) == 0
    assert calls == ["withdraw", "update_idletasks", "destroy"]


def test_alias_app_generation_options_without_mainloop() -> None:
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.map_var.set("ru-jcuken, uk-jcuken")
        app.include_full_name_var.set(True)
        app.min_token_var.set(5)

        options = app.generation_options()

        assert options.map_names == ["ru-jcuken", "uk-jcuken"]
        assert options.include_full_name is True
        assert options.min_token_length == 5

        app.use_toml_filters.set(False)
        app.exclude_cyrillic_only.set(False)
        settings = app.settings()

        assert settings.use_deny_list_filters is False
        assert settings.exclude_cyrillic_only_names is False
    finally:
        root.destroy()


def test_generate_tab_uses_table_with_number_app_and_path(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0, "microsoft-autogenerated": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates(
            [
                AppCandidate("Google Chrome", "chrome", content_c1=r"C:\Programs\Chrome.lnk"),
                AppCandidate("VLC", "vlc", content_c1=r"C:\Programs\VLC.lnk"),
            ]
        )
        app.search_var.set("chrome")

        children = app.candidate_tree.get_children()

        assert len(children) == 1
        assert app.candidate_tree.item(children[0], "values") == (
            ui.UNCHECKED_MARK,
            "1",
            "Google Chrome",
            r"C:\Programs\Chrome.lnk",
        )
    finally:
        root.destroy()


def test_generate_candidates_can_be_sorted_by_header(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates(
            [
                AppCandidate("VLC", "vlc", content_c1=r"C:\Programs\VLC.lnk"),
                AppCandidate("MPC-HC", "mpc-hc", content_c1=r"C:\Audio\MPC-HC.lnk"),
                AppCandidate("Google Chrome", "chrome", content_c1=r"C:\Browsers\Chrome.lnk"),
            ]
        )

        app.sort_tree_by(app.candidate_tree_state, "app", app.filter_candidates)

        assert [candidate.display_name for candidate in app.visible_candidates] == ["Google Chrome", "MPC-HC", "VLC"]
        assert app.candidate_tree.heading("app", "text") == "App ^"

        app.sort_tree_by(app.candidate_tree_state, "app", app.filter_candidates)

        assert [candidate.display_name for candidate in app.visible_candidates] == ["VLC", "MPC-HC", "Google Chrome"]
        assert app.candidate_tree.heading("app", "text") == "App v"

        app.sort_tree_by(app.candidate_tree_state, "path", app.filter_candidates)

        assert [candidate.display_name for candidate in app.visible_candidates] == ["MPC-HC", "Google Chrome", "VLC"]
        assert app.candidate_tree.heading("path", "text") == "Path ^"

        app.sort_tree_by(app.candidate_tree_state, "number", app.filter_candidates)

        assert [candidate.display_name for candidate in app.visible_candidates] == ["VLC", "MPC-HC", "Google Chrome"]
        assert app.candidate_tree.heading("number", "text") == "# ^"
    finally:
        root.destroy()


def test_alias_app_autoloads_apps_when_database_exists(monkeypatch, tmp_path) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui.ops, "resolve_db_path", lambda _db=None: tmp_path / "AppsIndex.db")
    monkeypatch.setattr(ui.ops, "eligible_candidates", lambda _settings: [AppCandidate("VLC", "vlc")])
    monkeypatch.setattr(ui.AliasApp, "run_task", lambda _self, _label, worker, done: done(worker()))
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)

        assert app.candidates == [AppCandidate("VLC", "vlc")]
        assert len(app.candidate_tree.get_children()) == 1
    finally:
        root.destroy()


def test_background_task_workers_use_captured_settings(monkeypatch) -> None:
    settings = ui.ops.AppSettings(db="snapshot.db")
    captured_workers = []
    inside_worker = False

    def settings_guard():
        if inside_worker:
            raise AssertionError("settings() must be captured before starting the background worker")
        return settings

    def run_task(_label, worker, _done):
        captured_workers.append(worker)

    def assert_settings(seen_settings):
        assert seen_settings is settings

    monkeypatch.setattr(ui.ops, "scan_database", lambda seen_settings: assert_settings(seen_settings))
    monkeypatch.setattr(ui.ops, "eligible_candidates", lambda seen_settings: assert_settings(seen_settings) or [])
    monkeypatch.setattr(
        ui.ops,
        "managed_alias_rows",
        lambda seen_settings, _kinds=None: assert_settings(seen_settings) or [],
    )
    monkeypatch.setattr(ui.ops, "backup_infos", lambda seen_settings: assert_settings(seen_settings) or [])

    app = SimpleNamespace(
        settings=settings_guard,
        run_task=run_task,
        remove_kind_var=SimpleNamespace(get=lambda: "all"),
        _show_backups=lambda _result: None,
        _show_managed=lambda _result: None,
        _show_scan=lambda _result: None,
        _set_candidates_with_scan=lambda _result: None,
    )

    ui.AliasApp.scan(app)  # type: ignore
    ui.AliasApp.load_candidates(app)  # type: ignore
    ui.AliasApp.refresh_managed(app)  # type: ignore
    ui.AliasApp.refresh_backups(app)  # type: ignore

    inside_worker = True
    for worker in captured_workers:
        worker()


def test_generate_candidates_are_checked_not_just_highlighted(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates(
            [
                AppCandidate("Google Chrome", "chrome"),
                AppCandidate("VLC", "vlc"),
            ]
        )
        app.candidate_tree.selection_set("0", "1")

        assert app.selected_candidates() == []

        app.check_highlighted_candidates()

        assert app.selected_candidates() == [
            AppCandidate("Google Chrome", "chrome"),
            AppCandidate("VLC", "vlc"),
        ]
        assert app.candidate_tree.item("0", "values")[0] == ui.CHECKED_MARK
        assert app.candidate_tree.item("1", "values")[0] == ui.CHECKED_MARK
    finally:
        root.destroy()


def test_space_toggles_highlighted_candidate_checks(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates([AppCandidate("VLC", "vlc")])
        app.candidate_tree.selection_set("0")

        assert app.toggle_highlighted_candidates_event(None) == "break"

        assert app.selected_candidates() == [AppCandidate("VLC", "vlc")]
    finally:
        root.destroy()


def test_arrow_keys_move_after_space_toggles_candidate_check(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates([AppCandidate("Google Chrome", "chrome"), AppCandidate("VLC", "vlc")])
        app.candidate_tree.selection_set("0")
        app.candidate_tree.focus("0")

        app.toggle_highlighted_candidates_event(None)
        assert app.move_candidate_selection_event(1) == "break"

        assert app.candidate_tree.selection() == ("1",)
        assert app.candidate_tree.focus() == "1"
        assert app.selected_candidates() == [AppCandidate("Google Chrome", "chrome")]
    finally:
        root.destroy()


def test_select_deselect_button_checks_or_unchecks_highlighted_candidates(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates([AppCandidate("Google Chrome", "chrome"), AppCandidate("VLC", "vlc")])
        app.checked_candidate_keys.add(app._candidate_key(app.visible_candidates[0]))
        app.candidate_tree.selection_set("0", "1")

        app.toggle_highlighted_candidates()

        assert app.selected_candidates() == [AppCandidate("Google Chrome", "chrome"), AppCandidate("VLC", "vlc")]

        app.toggle_highlighted_candidates()

        assert app.selected_candidates() == []
    finally:
        root.destroy()


def test_shift_arrows_extend_highlighted_candidate_selection(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates(
            [
                AppCandidate("Google Chrome", "chrome"),
                AppCandidate("MPC-HC", "mpc-hc"),
                AppCandidate("VLC", "vlc"),
            ]
        )
        app.candidate_tree.selection_set("0")
        app.candidate_tree.focus("0")

        assert app.extend_candidate_selection_event(1) == "break"
        assert app.extend_candidate_selection_event(1) == "break"

        assert app.candidate_tree.selection() == ("0", "1", "2")
        assert app.selected_candidates() == []

        app.toggle_highlighted_candidates()

        assert app.selected_candidates() == [
            AppCandidate("Google Chrome", "chrome"),
            AppCandidate("MPC-HC", "mpc-hc"),
            AppCandidate("VLC", "vlc"),
        ]
    finally:
        root.destroy()


def test_shift_arrows_can_shrink_highlighted_candidate_selection(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates(
            [
                AppCandidate("Google Chrome", "chrome"),
                AppCandidate("MPC-HC", "mpc-hc"),
                AppCandidate("VLC", "vlc"),
            ]
        )
        app.candidate_tree.selection_set("0")
        app.candidate_tree.focus("0")

        app.extend_candidate_selection(1)
        app.extend_candidate_selection(1)
        app.extend_candidate_selection(-1)

        assert app.candidate_tree.selection() == ("0", "1")
    finally:
        root.destroy()


def test_generate_candidates_highlight_managed_alias_sources(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidate_alias_sources(
            [
                ManagedRow("Google Chrome", "сркщьу", 1, ui.SOURCE_GENERATED_AUTO),
                ManagedRow("VLC", "player", 1, ui.SOURCE_CUSTOM),
            ]
        )
        app._set_candidates(
            [
                AppCandidate("Google Chrome", "chrome"),
                AppCandidate("MPC-HC", "mpc-hc"),
                AppCandidate("VLC", "vlc"),
            ]
        )

        assert app.candidate_tree.item("0", "tags") == (ui.CANDIDATE_ALIAS_AUTO_TAG,)
        assert app.candidate_tree.item("1", "tags") == ""
        assert app.candidate_tree.item("2", "tags") == (ui.CANDIDATE_ALIAS_CUSTOM_TAG,)
    finally:
        root.destroy()


def test_managed_rows_highlight_manual_and_custom_sources(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)

        app._show_managed(
            [
                ManagedRow("Google Chrome", "сркщьу", 1, ui.SOURCE_GENERATED_MANUAL),
                ManagedRow("VLC", "player", 1, ui.SOURCE_CUSTOM),
            ]
        )
        children = app.managed_tree.get_children()

        assert app.managed_tree.item(children[0], "tags") == (ui.CANDIDATE_ALIAS_MANUAL_TAG,)
        assert app.managed_tree.item(children[1], "tags") == (ui.CANDIDATE_ALIAS_CUSTOM_TAG,)
    finally:
        root.destroy()


def test_managed_shift_arrows_extend_highlighted_selection(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._show_managed(
            [
                ManagedRow("Google Chrome", "сркщьу", 1, ui.SOURCE_GENERATED_AUTO),
                ManagedRow("MPC-HC", "ьзс-рс", 1, ui.SOURCE_GENERATED_MANUAL),
                ManagedRow("VLC", "player", 1, ui.SOURCE_CUSTOM),
            ]
        )
        app.managed_tree.selection_set("0")
        app.managed_tree.focus("0")

        assert (
            app._extend_tree_selection_event(app.managed_tree, app.managed_tree_state, app._managed_count, 1) == "break"
        )
        assert (
            app._extend_tree_selection_event(app.managed_tree, app.managed_tree_state, app._managed_count, 1) == "break"
        )

        assert app.managed_tree.selection() == ("0", "1", "2")
    finally:
        root.destroy()


def test_managed_rows_can_be_checked_with_space_and_select_button(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._show_managed(
            [
                ManagedRow("Google Chrome", "сркщьу", 1, ui.SOURCE_GENERATED_AUTO),
                ManagedRow("VLC", "player", 1, ui.SOURCE_CUSTOM),
            ]
        )
        app.managed_tree.selection_set("0", "1")
        app.managed_tree.focus("0")

        assert (
            app._toggle_highlighted_tree_items_event(
                app.managed_tree,
                app.managed_tree_state,
                app._managed_count,
                app._managed_record_for_item,
                app.checked_managed_records,
                app._refresh_managed_tree_marks,
            )
            == "break"
        )

        assert app.managed_tree.item("0", "values")[0] == ui.CHECKED_MARK
        assert app.managed_tree.item("1", "values")[0] == ui.CHECKED_MARK

        app.toggle_highlighted_managed()

        assert app.checked_managed_records == set()
        assert app.managed_tree.item("0", "values")[0] == ui.UNCHECKED_MARK
        assert app.managed_tree.item("1", "values")[0] == ui.UNCHECKED_MARK
    finally:
        root.destroy()


def test_add_synonym_button_is_visible_for_one_highlighted_candidate(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._set_candidates([AppCandidate("VLC", "vlc"), AppCandidate("MPC-HC", "mpc-hc")])

        assert "disabled" in app.add_synonym_button.state()

        app.candidate_tree.selection_set("0")
        app.update_add_synonym_button_visibility()

        assert "disabled" not in app.add_synonym_button.state()

        app.candidate_tree.selection_set("0", "1")
        app.update_add_synonym_button_visibility()

        assert "disabled" in app.add_synonym_button.state()
    finally:
        root.destroy()


def test_add_custom_alias_prompts_for_synonym(monkeypatch) -> None:
    seen = {}
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_synonym", lambda _master: "player")

    def fake_preview(worker, question):
        seen["plan"] = worker()
        seen["question"] = question

    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._preview_then_apply = fake_preview  # type: ignore
        app._set_candidates([AppCandidate("VLC", "vlc")])
        app.candidate_tree.selection_set("0")

        app.add_custom_alias()

        assert seen["plan"].groups[0].display_name == "VLC"
        assert [alias.synonym for alias in seen["plan"].groups[0].aliases] == ["player"]
        assert seen["question"] == "Add custom aliases?"
    finally:
        root.destroy()


def test_filter_menu_change_reloads_apps(monkeypatch, tmp_path) -> None:
    calls = []
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 1})
    monkeypatch.setattr(ui.ops, "resolve_db_path", lambda _db=None: tmp_path / "AppsIndex.db")

    def fake_candidates(settings):
        calls.append(tuple(settings.included_content_categories))
        return [AppCandidate("VLC", "vlc")]

    monkeypatch.setattr(ui.ops, "eligible_candidates", fake_candidates)
    monkeypatch.setattr(ui.AliasApp, "run_task", lambda _self, _label, worker, done: done(worker()))
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.category_vars["games"].set(False)

        app.update_filter_categories()

        assert calls[-1] == ("games",)
    finally:
        root.destroy()


def test_filter_menu_toml_toggle_reloads_apps(monkeypatch, tmp_path) -> None:
    calls = []
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 1})
    monkeypatch.setattr(ui.ops, "resolve_db_path", lambda _db=None: tmp_path / "AppsIndex.db")

    def fake_candidates(settings):
        calls.append(settings.use_deny_list_filters)
        return [AppCandidate("VLC", "vlc")]

    monkeypatch.setattr(ui.ops, "eligible_candidates", fake_candidates)
    monkeypatch.setattr(ui.AliasApp, "run_task", lambda _self, _label, worker, done: done(worker()))
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.use_toml_filters.set(False)

        app.update_filter_settings()

        assert calls[-1] is False
    finally:
        root.destroy()


def test_filter_categories_stay_editable_when_toml_filters_are_off(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 1})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.use_toml_filters.set(False)
        app.refresh_filters()

        category_index = 3

        assert app.filter_menu.entrycget(category_index, "state") == "normal"
    finally:
        root.destroy()


def test_apps_index_menu_confirms_custom_path_when_auto_db_exists(monkeypatch, tmp_path) -> None:
    auto_db = tmp_path / "auto" / "AppsIndex.db"
    custom_db = tmp_path / "custom" / "AppsIndex.db"
    asked = {}  # type: ignore
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui.ops, "resolve_db_path", lambda _db=None: auto_db)
    monkeypatch.setattr(ui.ops, "eligible_candidates", lambda _settings: [])
    monkeypatch.setattr(ui.AliasApp, "run_task", lambda _self, _label, worker, done: done(worker()))
    monkeypatch.setattr(
        ui, "ask_yes_no", lambda _master, title, message: asked.update(title=title, message=message) or True
    )
    monkeypatch.setattr(ui.filedialog, "askopenfilename", lambda **_kwargs: str(custom_db))
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)

        app.browse_db()

        assert str(auto_db) in asked["message"]
        assert app.db_var.get() == str(custom_db)
    finally:
        root.destroy()


def test_dashboard_is_rendered_as_panel_instead_of_tab(monkeypatch) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        notebook = next(child for child in app.winfo_children() if isinstance(child, ui.ttk.Notebook))
        tab_labels = [notebook.tab(tab_id, "text") for tab_id in notebook.tabs()]

        assert "Dashboard" not in tab_labels
        assert app.total_entries_var.get() == "Total indexed entries: -"
        assert app.ignored_entries_var.get() == "Ignored by filtering rules: -"
    finally:
        root.destroy()


def test_scan_updates_dashboard_panel_counts(monkeypatch, tmp_path) -> None:
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    result = ui.ops.ScanResult(
        db_path=tmp_path / "AppsIndex.db",
        report=FilterReport(total=642, eligible=362, ignored=280, reason_counts={}),
        deny_list=load_deny_list(None),
        enabled_content_categories=set(),
    )
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)

        app._show_scan(result)

        assert app.total_entries_var.get() == "Total indexed entries: 642"
        assert app.ignored_entries_var.get() == "Ignored by filtering rules: 280"
    finally:
        root.destroy()


def test_managed_remove_selected_rows_uses_exact_records(monkeypatch) -> None:
    seen = {}
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0, "microsoft-autogenerated": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_exact(_settings, records):
        seen["records"] = records
        return ui.ops.ApplyResult(removed=len(records))

    def fail_broad(*_args, **_kwargs):
        raise AssertionError("Selected rows should be removed exactly, not by app name.")

    monkeypatch.setattr(ui.ops, "remove_managed_alias_records_exact", fake_exact)
    monkeypatch.setattr(ui.ops, "remove_managed_aliases", fail_broad)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_managed(
            [
                ManagedRow("Google Chrome", "browser", 1, "WinSearchAliasesCustom"),
                ManagedRow("VLC", "player", 1, "WinSearchAliasesCustom"),
            ]
        )
        app.managed_tree.selection_set("0", "1")

        app.remove_managed()

        assert seen["records"] == {
            ("Google Chrome", "browser", "WinSearchAliasesCustom"),
            ("VLC", "player", "WinSearchAliasesCustom"),
        }
    finally:
        root.destroy()


def test_managed_remove_uses_checked_rows_before_highlighted_rows(monkeypatch) -> None:
    seen = {}
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_exact(_settings, records):
        seen["records"] = records
        return ui.ops.ApplyResult(removed=len(records))

    monkeypatch.setattr(ui.ops, "remove_managed_alias_records_exact", fake_exact)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_managed(
            [
                ManagedRow("Google Chrome", "browser", 1, "WinSearchAliasesCustom"),
                ManagedRow("VLC", "player", 1, "WinSearchAliasesCustom"),
            ]
        )
        app.managed_tree.selection_set("0")
        app.checked_managed_records.add(("VLC", "player", "WinSearchAliasesCustom"))

        app.remove_managed()

        assert seen["records"] == {("VLC", "player", "WinSearchAliasesCustom")}
    finally:
        root.destroy()


def test_backups_table_tags_clean_managed_and_error_rows() -> None:
    assert (
        ui.AliasApp._backup_tag(
            ui.ops.BackupInfo(path=Path("clean.db"), reason="test", created_at="now", status="clean: no managed rows")
        )
        == "clean"
    )
    assert (
        ui.AliasApp._backup_tag(
            ui.ops.BackupInfo(
                path=Path("managed.db"), reason="test", created_at="now", status="modified: managed rows: 1"
            )
        )
        == "managed"
    )
    assert (
        ui.AliasApp._backup_tag(
            ui.ops.BackupInfo(
                path=Path("missing.db"), reason="test", created_at="now", status="missing file", has_error=True
            )
        )
        == "error"
    )


def test_backup_delete_selected_calls_ui_api(monkeypatch, tmp_path) -> None:
    backup_path = tmp_path / "backup.db"
    seen = {}  # type: ignore
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_delete(_settings, path):
        seen.setdefault("paths", []).append(path)
        return ui.ops.DeleteBackupResult(path=path, removed_file=True, removed_metadata=1)

    monkeypatch.setattr(ui.ops, "delete_backup", fake_delete)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_backups(
            [ui.ops.BackupInfo(path=backup_path, reason="unit-test", created_at="now", status="clean: no managed rows")]
        )
        app.backup_tree.selection_set("0")

        app.delete_selected_backup()

        assert seen["paths"] == [backup_path]
    finally:
        root.destroy()


def test_backups_shift_arrows_extend_highlighted_selection(monkeypatch, tmp_path) -> None:
    first = tmp_path / "first.db"
    second = tmp_path / "second.db"
    third = tmp_path / "third.db"
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._show_backups(
            [
                ui.ops.BackupInfo(path=first, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(path=second, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(path=third, reason="unit-test", created_at="now", status="clean: no managed rows"),
            ]
        )
        app.backup_tree.selection_set("0")
        app.backup_tree.focus("0")

        assert app._extend_tree_selection_event(app.backup_tree, app.backup_tree_state, app._backup_count, 1) == "break"
        assert app._extend_tree_selection_event(app.backup_tree, app.backup_tree_state, app._backup_count, 1) == "break"

        assert app.backup_tree.selection() == ("0", "1", "2")
    finally:
        root.destroy()


def test_backups_can_be_checked_with_space_and_select_button(monkeypatch, tmp_path) -> None:
    first = tmp_path / "first.db"
    second = tmp_path / "second.db"
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app._show_backups(
            [
                ui.ops.BackupInfo(path=first, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(path=second, reason="unit-test", created_at="now", status="clean: no managed rows"),
            ]
        )
        app.backup_tree.selection_set("0", "1")
        app.backup_tree.focus("0")

        assert (
            app._toggle_highlighted_tree_items_event(
                app.backup_tree,
                app.backup_tree_state,
                app._backup_count,
                app._backup_path_for_item,
                app.checked_backup_paths,
                app._refresh_backup_tree_marks,
            )
            == "break"
        )

        assert app.backup_tree.item("0", "values")[0] == ui.CHECKED_MARK
        assert app.backup_tree.item("1", "values")[0] == ui.CHECKED_MARK

        app.toggle_highlighted_backups()

        assert app.checked_backup_paths == set()
        assert app.backup_tree.item("0", "values")[0] == ui.UNCHECKED_MARK
        assert app.backup_tree.item("1", "values")[0] == ui.UNCHECKED_MARK
    finally:
        root.destroy()


def test_backup_restore_uses_checked_backup_before_highlighted_backup(monkeypatch, tmp_path) -> None:
    first = tmp_path / "first.db"
    second = tmp_path / "second.db"
    seen = {}
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_restore(_settings, path):
        seen["path"] = path
        return ui.ops.ApplyResult(backup=tmp_path / "safety.db")

    monkeypatch.setattr(ui.ops, "restore_backup", fake_restore)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_backups(
            [
                ui.ops.BackupInfo(path=first, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(path=second, reason="unit-test", created_at="now", status="clean: no managed rows"),
            ]
        )
        app.backup_tree.selection_set("0")
        app.checked_backup_paths.add(second)

        app.restore_selected_backup()

        assert seen["path"] == second
    finally:
        root.destroy()


def test_backup_delete_uses_checked_backups_before_highlighted_backups(monkeypatch, tmp_path) -> None:
    first = tmp_path / "first.db"
    second = tmp_path / "second.db"
    seen = {}  # type: ignore
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_delete(_settings, path):
        seen.setdefault("paths", []).append(path)
        return ui.ops.DeleteBackupResult(path=path, removed_file=True, removed_metadata=1)

    monkeypatch.setattr(ui.ops, "delete_backup", fake_delete)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_backups(
            [
                ui.ops.BackupInfo(path=first, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(path=second, reason="unit-test", created_at="now", status="clean: no managed rows"),
            ]
        )
        app.backup_tree.selection_set("0")
        app.checked_backup_paths.add(second)

        app.delete_selected_backup()

        assert seen["paths"] == [second]
    finally:
        root.destroy()


def test_backup_delete_selected_handles_multiple_backups(monkeypatch, tmp_path) -> None:
    first = tmp_path / "first.db"
    second = tmp_path / "second.db"
    seen = {}  # type: ignore
    monkeypatch.setattr(ui.ops, "managed_alias_rows", lambda _settings, _kinds=None: [])
    monkeypatch.setattr(ui.ops, "backup_infos", lambda _settings: [])
    monkeypatch.setattr(ui.ops, "filter_category_counts", lambda _settings: {"games": 0})
    monkeypatch.setattr(ui, "ask_yes_no", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(ui, "show_message", lambda *_args, **_kwargs: None)

    def fake_delete(_settings, path):
        seen.setdefault("paths", []).append(path)
        return ui.ops.DeleteBackupResult(path=path, removed_file=True, removed_metadata=1)

    monkeypatch.setattr(ui.ops, "delete_backup", fake_delete)
    try:
        root = ui.tk.Tk()
    except ui.tk.TclError as exc:
        pytest.skip(f"Tk display is unavailable: {exc}")
    root.withdraw()
    try:
        app = ui.AliasApp(root)
        app.run_task = lambda _label, worker, done: done(worker())  # type: ignore
        app._show_backups(
            [
                ui.ops.BackupInfo(path=first, reason="unit-test", created_at="now", status="clean: no managed rows"),
                ui.ops.BackupInfo(
                    path=second, reason="unit-test", created_at="now", status="modified: managed rows: 1"
                ),
            ]
        )
        app.backup_tree.selection_set("0", "1")

        app.delete_selected_backup()

        assert seen["paths"] == [first, second]
    finally:
        root.destroy()
